# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1

    - name: ls 
      run: ls 


    - name: Build
      run: go build -v ./...

    - name: ls 
      run: ls 

    - name: Test
      run: go test -v ./...

      
    - name: run
      env:
        MYSQL_DSN: ${{ secrets.MYSQL_DSN }}
      run: ./url_shorten_service
